### ISSUE TITLE
Checklist: Prepare on call staff for success

### ISSUE THREAD

**Issue by porta-antiporta** [usagov/test-at-home#221]
Topics to cover
## Provision
- [x] cloud.gov spaces
- [x] new relic
- [x] github
- [x] Slack alerts

## Training
- [x] ~~Local build~~
- [x] Walk through NR

## Process
- [x] Service Now phone configuration

# Acceptance criteria
- [x] issue template for onboarding new on call folks
- [x] wiki article reflecting issue
